/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_illinois_library_poppler_PopplerPageRenderer */

#ifndef _Included_edu_illinois_library_poppler_PopplerPageRenderer
#define _Included_edu_illinois_library_poppler_PopplerPageRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_illinois_library_poppler_PopplerPageRenderer
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_illinois_library_poppler_PopplerPageRenderer_initialize
  (JNIEnv *, jobject);

/*
 * Class:     edu_illinois_library_poppler_PopplerPageRenderer
 * Method:    nativeDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_illinois_library_poppler_PopplerPageRenderer_nativeDestroy
  (JNIEnv *, jobject);

/*
 * Class:     edu_illinois_library_poppler_PopplerPageRenderer
 * Method:    nativeGetImageFormat
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_illinois_library_poppler_PopplerPageRenderer_nativeGetImageFormat
  (JNIEnv *, jobject);

/*
 * Class:     edu_illinois_library_poppler_PopplerPageRenderer
 * Method:    nativeSetImageFormat
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_illinois_library_poppler_PopplerPageRenderer_nativeSetImageFormat
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_illinois_library_poppler_PopplerPageRenderer
 * Method:    nativeSetRenderHint
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_illinois_library_poppler_PopplerPageRenderer_nativeSetRenderHint
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_illinois_library_poppler_PopplerPageRenderer
 * Method:    canRender
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_edu_illinois_library_poppler_PopplerPageRenderer_canRender
  (JNIEnv *, jobject);

/*
 * Class:     edu_illinois_library_poppler_PopplerPageRenderer
 * Method:    renderPage
 * Signature: (Ledu/illinois/library/poppler/PopplerPage;DDIIII)Ledu/illinois/library/poppler/PopplerImage;
 */
JNIEXPORT jobject JNICALL Java_edu_illinois_library_poppler_PopplerPageRenderer_renderPage
  (JNIEnv *, jobject, jobject, jdouble, jdouble, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
