/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_illinois_library_poppler_PopplerDocument */

#ifndef _Included_edu_illinois_library_poppler_PopplerDocument
#define _Included_edu_illinois_library_poppler_PopplerDocument
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_illinois_library_poppler_PopplerDocument
 * Method:    loadFromData
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_edu_illinois_library_poppler_PopplerDocument_loadFromData
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     edu_illinois_library_poppler_PopplerDocument
 * Method:    loadFromFile
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_edu_illinois_library_poppler_PopplerDocument_loadFromFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     edu_illinois_library_poppler_PopplerDocument
 * Method:    createPage
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_edu_illinois_library_poppler_PopplerDocument_createPage
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_illinois_library_poppler_PopplerDocument
 * Method:    getAuthor
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_illinois_library_poppler_PopplerDocument_getAuthor
  (JNIEnv *, jobject);

/*
 * Class:     edu_illinois_library_poppler_PopplerDocument
 * Method:    getNativeCreationDate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_illinois_library_poppler_PopplerDocument_getNativeCreationDate
  (JNIEnv *, jobject);

/*
 * Class:     edu_illinois_library_poppler_PopplerDocument
 * Method:    getCreator
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_illinois_library_poppler_PopplerDocument_getCreator
  (JNIEnv *, jobject);

/*
 * Class:     edu_illinois_library_poppler_PopplerDocument
 * Method:    getKeywords
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_illinois_library_poppler_PopplerDocument_getKeywords
  (JNIEnv *, jobject);

/*
 * Class:     edu_illinois_library_poppler_PopplerDocument
 * Method:    getNativeModificationDate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_illinois_library_poppler_PopplerDocument_getNativeModificationDate
  (JNIEnv *, jobject);

/*
 * Class:     edu_illinois_library_poppler_PopplerDocument
 * Method:    getProducer
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_illinois_library_poppler_PopplerDocument_getProducer
  (JNIEnv *, jobject);

/*
 * Class:     edu_illinois_library_poppler_PopplerDocument
 * Method:    getSubject
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_illinois_library_poppler_PopplerDocument_getSubject
  (JNIEnv *, jobject);

/*
 * Class:     edu_illinois_library_poppler_PopplerDocument
 * Method:    getTitle
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_illinois_library_poppler_PopplerDocument_getTitle
  (JNIEnv *, jobject);

/*
 * Class:     edu_illinois_library_poppler_PopplerDocument
 * Method:    isEncrypted
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_edu_illinois_library_poppler_PopplerDocument_isEncrypted
  (JNIEnv *, jobject);

/*
 * Class:     edu_illinois_library_poppler_PopplerDocument
 * Method:    isLocked
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_edu_illinois_library_poppler_PopplerDocument_isLocked
  (JNIEnv *, jobject);

/*
 * Class:     edu_illinois_library_poppler_PopplerDocument
 * Method:    metadata
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_illinois_library_poppler_PopplerDocument_metadata
  (JNIEnv *, jobject);

/*
 * Class:     edu_illinois_library_poppler_PopplerDocument
 * Method:    nativeDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_illinois_library_poppler_PopplerDocument_nativeDestroy
  (JNIEnv *, jobject);

/*
 * Class:     edu_illinois_library_poppler_PopplerDocument
 * Method:    numPages
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_illinois_library_poppler_PopplerDocument_numPages
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
