/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_illinois_library_poppler_PopplerPage */

#ifndef _Included_edu_illinois_library_poppler_PopplerPage
#define _Included_edu_illinois_library_poppler_PopplerPage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_illinois_library_poppler_PopplerPage
 * Method:    getLabel
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_illinois_library_poppler_PopplerPage_getLabel
  (JNIEnv *, jobject);

/*
 * Class:     edu_illinois_library_poppler_PopplerPage
 * Method:    nativeDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_illinois_library_poppler_PopplerPage_nativeDestroy
  (JNIEnv *, jobject);

/*
 * Class:     edu_illinois_library_poppler_PopplerPage
 * Method:    orientation
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_illinois_library_poppler_PopplerPage_orientation
  (JNIEnv *, jobject);

/*
 * Class:     edu_illinois_library_poppler_PopplerPage
 * Method:    pageRect
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_edu_illinois_library_poppler_PopplerPage_pageRect
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
